sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "4.6.1"

before_install:
  - npm i -g npm@^2.0.0

install:
  - npm install typescript -g
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
  - webdriver-manager update --standalone --chrome
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - gulp > /dev/null & # start server
  - sleep 10 # give server time to start

script:
  - npm run compile
  - npm run test

after_success:
  - npm run semantic-release